name: Markdown Checks

on:
  push:
  pull_request:

# TODO: dart-fixer extension
jobs:
  # Check Markdown links
  markdown-link-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: gaurav-nelson/github-action-markdown-link-check@v1
        with:
          base-branch: main
          config-file: .github/markdown-link-check.config.json